### ISSUE TITLE
Job not starting

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#660]
`error: [gme:server:worker:simpleworker:pid_100889:WorkerFunctions:PluginManagerBase:plugin:ExecutePipeli
ne] TypeError: Cannot read property 'charAt' of null                                                                               
`

**Comment by brollb** [comment]
Can you check out the branch [660-job-not-starting](https://github.com/dfst/deepforge/tree/660-job-not-starting)? If you can replicate this issue on that branch, it should give a better idea of what is causing the error.

If you can't replicate it, I will probably merge that branch so that when it happens again, we can get a better idea of the cause...
