### ISSUE TITLE
Name collisions on lines in graphs

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#675]
If lines have the same name, only one shows up.

**Comment by brollb** [comment]
There are three cases where this can be a problem:
- Two lines w/ the same name in one graph
- Two graphs using the same line names shown in the execution index
- Two graphs for the same execution w/ colliding names of lines

I think they should be handled as follows:
- lines w/ the same name in a single `deepforge.Graph` should simply add `(2)`, `(3)`, etc
  - based on some arbitrary tie breaking rule (say the sorting of the relids)

- lines colliding between graphs of different executions
  - add `(<execId>)` where the `<execId>` is also shown in the ExecIndex
  - this should probably be done for all the lines regardless of collisions
  - should probably be an abbreviation rather than simply a count
    - this will allow them to be distinguishable from the earlier bullet (in case both cases happen at once)

- lines colliding between graphs of same execution in ExecIndex
  - handled the same as the first bullet

**Comment by brollb** [comment]
For now, I am just going to address the second bullet point.  The first bullet point is easy to modify from the user's point of view (just given the lines on a single graph unique names!)
